version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 4200:4200
    volumes:
      - ./:/app
    container_name: mjars
    environment:
      - CHOKIDAR_USEPOLLING=true
