FROM node:16.13.1-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY ./package*.json /usr/src/app/
RUN npm cache clean
RUN npm install -g @angular/cli
COPY . /usr/src/app/
EXPOSE 4200
CMD npm start
