# Step 1
FROM node:16.13.1-alpine as build-step
WORKDIR /app
COPY ./package.json /app
RUN npm install -g @angular/cli
COPY . /app
EXPOSE 4200
RUN npm run build

# Step 2
FROM nginx:1.23.1-alpine
COPY --from=build-step app/dist/client /usr/share/nginx/html
